-- Schema for retail banking
-- Originally written for Oracle (CSE 241, summer 2026); ported to PostgreSQL 17.
--
-- Four ISA hierarchies model the domain:
--   account          -> models checking | savings
--   card             -> models debit_card | credit_card
--   loan             -> models secured_loan | unsecured_loan
--   bank_transaction -> models purchase | loan_payment | stmnt_payment | transfer | account_activity
--
-- Each subtype table takes the supertype's key as both PRIMARY KEY and FOREIGN KEY,
-- which enforces 1:1 participation without duplicating the supertype's columns.

DROP TABLE IF EXISTS account_activity, transfer, stmnt_payment, loan_payment, purchase,
                     bank_transaction, collateral, unsecured_loan, secured_loan, borrows,
                     loan, credit_card, debit_card, card, owns, savings, checking,
                     account, vendor, branch, client CASCADE;

-- ---------------------------------------------------------------- entities

CREATE TABLE client (
    client_id     INTEGER       PRIMARY KEY,
    name          VARCHAR(100)  NOT NULL,
    address       VARCHAR(200)
);

CREATE TABLE branch (
    branch_id     INTEGER       PRIMARY KEY,
    address       VARCHAR(200)  NOT NULL,
    has_teller    CHAR(1)       DEFAULT 'N' NOT NULL
        CHECK (has_teller IN ('Y','N'))
);

CREATE TABLE vendor (
    vendor_id     INTEGER       PRIMARY KEY,
    name          VARCHAR(100)  NOT NULL
);

-- ---------------------------------------------------------------- accounts

CREATE TABLE account (
    accountnum    INTEGER       PRIMARY KEY,
    balance       NUMERIC(12,2) DEFAULT 0 NOT NULL,
    interest_rate NUMERIC(5,3),
    date_opened   DATE          NOT NULL,
    account_type  VARCHAR(10)   NOT NULL
        CHECK (account_type IN ('CHECKING','SAVINGS'))
);

CREATE TABLE checking (
    accountnum    INTEGER       PRIMARY KEY REFERENCES account(accountnum),
    monthly_fee   NUMERIC(6,2)  DEFAULT 0 NOT NULL
);

CREATE TABLE savings (
    accountnum    INTEGER       PRIMARY KEY REFERENCES account(accountnum),
    min_balance   NUMERIC(12,2) NOT NULL,
    penalty       NUMERIC(8,2)  NOT NULL
);

-- M:N — an account can have several owners (joint accounts), a client several accounts
CREATE TABLE owns (
    client_id     INTEGER       REFERENCES client(client_id),
    accountnum    INTEGER       REFERENCES account(accountnum),
    PRIMARY KEY (client_id, accountnum)
);

-- ---------------------------------------------------------------- cards

CREATE TABLE card (
    card_number   VARCHAR(16)   PRIMARY KEY,
    expiration    DATE          NOT NULL,
    card_type     VARCHAR(6)    NOT NULL
        CHECK (card_type IN ('DEBIT','CREDIT')),
    client_id     INTEGER       NOT NULL REFERENCES client(client_id)
);

CREATE TABLE debit_card (
    card_number      VARCHAR(16)  PRIMARY KEY REFERENCES card(card_number),
    withdrawal_limit NUMERIC(8,2) DEFAULT 500 NOT NULL,
    accountnum       INTEGER      NOT NULL REFERENCES checking(accountnum)
);

CREATE TABLE credit_card (
    card_number     VARCHAR(16)   PRIMARY KEY REFERENCES card(card_number),
    interest_rate   NUMERIC(5,3)  NOT NULL,
    credit_limit    NUMERIC(10,2) NOT NULL,
    running_balance NUMERIC(12,2) DEFAULT 0 NOT NULL,
    balance_due     NUMERIC(12,2) DEFAULT 0 NOT NULL
);

-- ---------------------------------------------------------------- loans

CREATE TABLE loan (
    loan_id         INTEGER       PRIMARY KEY,
    loan_balance    NUMERIC(12,2) NOT NULL,
    interest_rate   NUMERIC(5,3)  NOT NULL,
    monthly_payment NUMERIC(10,2) NOT NULL,
    loan_type       VARCHAR(9)    NOT NULL
        CHECK (loan_type IN ('SECURED','UNSECURED'))
);

-- M:N — co-signed loans have more than one borrower
CREATE TABLE borrows (
    client_id     INTEGER        REFERENCES client(client_id),
    loan_id       INTEGER        REFERENCES loan(loan_id),
    PRIMARY KEY (client_id, loan_id)
);

CREATE TABLE secured_loan (
    loan_id             INTEGER      PRIMARY KEY REFERENCES loan(loan_id),
    loan_to_value_ratio NUMERIC(5,2)
);

CREATE TABLE unsecured_loan (
    loan_id                  INTEGER PRIMARY KEY REFERENCES loan(loan_id),
    credit_score_at_approval SMALLINT
);

CREATE TABLE collateral (
    collateral_id   INTEGER       PRIMARY KEY,
    appraised_value NUMERIC(12,2) NOT NULL,
    loan_id         INTEGER       NOT NULL REFERENCES secured_loan(loan_id)
);

-- ---------------------------------------------------------------- transactions

CREATE TABLE bank_transaction (
    transaction_id    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_value NUMERIC(12,2) NOT NULL,
    txn_timestamp     TIMESTAMPTZ  DEFAULT now() NOT NULL,
    transaction_type  VARCHAR(16)  NOT NULL
        CHECK (transaction_type IN
          ('PURCHASE','LOAN_PAYMENT','STMNT_PAYMENT','TRANSFER','ACCT_ACTIVITY')),
    branch_id         INTEGER      REFERENCES branch(branch_id)
);

CREATE TABLE purchase (
    transaction_id BIGINT      PRIMARY KEY REFERENCES bank_transaction(transaction_id),
    vendor_id      INTEGER     NOT NULL REFERENCES vendor(vendor_id),
    card_number    VARCHAR(16) NOT NULL REFERENCES card(card_number)
);

CREATE TABLE loan_payment (
    transaction_id BIGINT  PRIMARY KEY REFERENCES bank_transaction(transaction_id),
    loan_id        INTEGER NOT NULL REFERENCES loan(loan_id)
);

CREATE TABLE stmnt_payment (
    transaction_id BIGINT      PRIMARY KEY REFERENCES bank_transaction(transaction_id),
    card_number    VARCHAR(16) NOT NULL REFERENCES credit_card(card_number)
);

CREATE TABLE transfer (
    transaction_id  BIGINT  PRIMARY KEY REFERENCES bank_transaction(transaction_id),
    from_accountnum INTEGER NOT NULL REFERENCES account(accountnum),
    to_accountnum   INTEGER NOT NULL REFERENCES account(accountnum),
    CHECK (from_accountnum <> to_accountnum)
);

CREATE TABLE account_activity (
    transaction_id BIGINT      PRIMARY KEY REFERENCES bank_transaction(transaction_id),
    accountnum     INTEGER     NOT NULL REFERENCES account(accountnum),
    activity_type  VARCHAR(10) NOT NULL
        CHECK (activity_type IN ('DEPOSIT','WITHDRAWAL'))
);
